export const PLAYERS_COORDS = {
  1: [{ col: 6, row: 1, colSpan: 2, rowSpan: 2 }],
  2: [
    { col: 2, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 10, row: 1, colSpan: 2, rowSpan: 2 },
  ],
  3: [
    { col: 2, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 6, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 10, row: 1, colSpan: 2, rowSpan: 2 },
  ],
  4: [
    { col: 4, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 8, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 4, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 4, colSpan: 2, rowSpan: 2 },
  ],
  5: [
    { col: 3, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 6, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 9, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 4, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 4, colSpan: 2, rowSpan: 2 },
  ],
  6: [
    { col: 3, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 9, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 3, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 3, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 6, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 6, colSpan: 2, rowSpan: 2 },
  ],
  7: [
    { col: 3, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 6, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 9, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 3, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 3, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 6, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 6, colSpan: 2, rowSpan: 2 },
  ],
  8: [
    { col: 3, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 9, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 2, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 2, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 5, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 5, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 8, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 8, colSpan: 2, rowSpan: 2 },
  ],
  9: [
    { col: 3, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 6, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 9, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 2, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 2, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 5, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 5, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 8, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 8, colSpan: 2, rowSpan: 2 },
  ],
  10: [
    { col: 3, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 5, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 7, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 9, row: 1, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 2, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 2, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 5, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 5, colSpan: 2, rowSpan: 2 },
    { col: 1, row: 8, colSpan: 2, rowSpan: 2 },
    { col: 11, row: 8, colSpan: 2, rowSpan: 2 },
  ],
}
